name = input("Enter the name of the person: ")
id = input("Enter the id of the person: ")
centre = input("Enter the centre(s) the person works at: ")
designation = input("Enter the designation of the person: ")
joinDate = input("when did they join? ")
